In [31]:
import numpy as np

In [32]:
arr = np.array([2,3,4,5,6])


In [33]:
arr

array([2, 3, 4, 5, 6])

In [34]:
arr[3]

np.int64(5)

In [35]:
 arr2 = np.array([[1,2,3,4],[6,7,8,9]])
arr2


array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [36]:
arr2[1,3]


np.int64(9)

In [37]:
arr3 = np.array([[11,12,13],[15,16,27],[45,67,'NULL']])
arr3


array([['11', '12', '13'],
       ['15', '16', '27'],
       ['45', '67', 'NULL']], dtype='<U21')

In [38]:
arr3[2,2]=33

In [39]:
arr3

array([['11', '12', '13'],
       ['15', '16', '27'],
       ['45', '67', '33']], dtype='<U21')

In [40]:
arr3.shape

(3, 3)

In [41]:
arr3.size

9

In [42]:
arr3.dtype

dtype('<U21')

In [43]:
np.array({22,44,66})


array({66, 44, 22}, dtype=object)

In [44]:
an = np.zeros((3,4))
an

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
rng = np.arange(14)

In [46]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [47]:
lspace = np.linspace(1,3,5)

In [48]:
lspace

array([1. , 1.5, 2. , 2.5, 3. ])

In [49]:
emp = np.empty((3,3))
emp


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [50]:
emp_like = np.empty_like(lspace)

In [51]:
emp_like

array([1. , 1.5, 2. , 2.5, 3. ])

In [52]:
ide = np.identity(5)
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
ide.shape

(5, 5)

In [54]:
arr = np.arange (99)

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [56]:
arr.reshape(9,11)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76],
       [77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87],
       [88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [57]:
arr3 = arr3.ravel()
arr3

array(['11', '12', '13', '15', '16', '27', '45', '67', '33'], dtype='<U21')

In [58]:
x = [[1,2,3],[5,6,7],[12,45,67]]

In [59]:
ar = np.array(x)

In [60]:
ar

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [12, 45, 67]])

In [64]:
ar.sum(axis=1)


array([  6,  18, 124])

In [65]:
ar.sum(axis=0)

array([18, 53, 77])

In [66]:
ar.T

array([[ 1,  5, 12],
       [ 2,  6, 45],
       [ 3,  7, 67]])

In [68]:
ar.flat

In [71]:
for item in ar.flat:
    print(item)

1
2
3
5
6
7
12
45
67


In [73]:
ar.ndim

2

In [74]:
ar.size

9

In [75]:
ar.nbytes

72

In [76]:
one = np.array([1,2,3,4,533])


In [79]:
one.argmax() ## gives the index of max element

np.int64(4)

In [80]:
one.argmin()

np.int64(0)

In [81]:
one.argsort()

array([0, 1, 2, 3, 4])

In [83]:
ar.argmin()

np.int64(0)

In [84]:
ar.argmax()

np.int64(8)

In [85]:
ar.argmax(axis=0)

array([2, 2, 2])

In [87]:
ar.argmax(axis=1)

array([2, 2, 2])

In [89]:
ar.argmin(axis=0)

array([0, 0, 0])

In [90]:
ar.ravel()


array([ 1,  2,  3,  5,  6,  7, 12, 45, 67])

In [92]:
ar.reshape((9,1))

array([[ 1],
       [ 2],
       [ 3],
       [ 5],
       [ 6],
       [ 7],
       [12],
       [45],
       [67]])

In [93]:
ar2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [94]:
ar + ar2

array([[ 2,  4,  6],
       [ 9, 11, 13],
       [19, 53, 76]])

In [95]:
ar * ar2

array([[  1,   4,   9],
       [ 20,  30,  42],
       [ 84, 360, 603]])

In [96]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.23606798, 2.44948974, 2.64575131],
       [3.46410162, 6.70820393, 8.18535277]])

In [97]:
np.sqrt(ar2)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [98]:
ar.sum()


np.int64(148)

In [100]:
ar.min()

np.int64(1)

In [101]:
ar.max()


np.int64(67)

In [102]:
ar

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [12, 45, 67]])

In [104]:
np.where(ar>10)

(array([2, 2, 2]), array([0, 1, 2]))

In [105]:
np.count_nonzero(ar)

9

In [106]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [107]:
ar[1,2]=0

In [108]:
ar

array([[ 1,  2,  3],
       [ 5,  6,  0],
       [12, 45, 67]])

In [109]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 0, 1, 2]))

In [110]:
import sys

In [111]:
ch_ar = [0,4,55,2]

In [113]:
np_ar = np.array(ch_ar)

In [114]:
sys.getsizeof(1) * len(ch_ar)

112

In [116]:
np_ar.itemsize * np_ar.size

32

In [119]:
ch=ar.tolist()

In [120]:
ch

[[1, 2, 3], [5, 6, 0], [12, 45, 67]]

In [122]:
for items in ch:
    print(items)

[1, 2, 3]
[5, 6, 0]
[12, 45, 67]
